version: '2.1'
services:
  # development environment links to [mongo, elastic, ...]

  # add mongo & elastic links to api
  api:
    links:
      - mongo
      - elastic


  # Mongo DB
  mongo:
    container_name: mongo
    image: "mongo:latest"
    volumes:
      - "./util:/util/"
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
    environment:
      - MONGO_DBNAME=${MONGO_DBNAME}          # defaults to 'test'

  # Elastic Search
  # note: on docker for mac, you may need to adjust the docker-machines' config
  # if you get this error ....
  # elastic    | ERROR: bootstrap checks failed
  # elastic    | max virtual memory areas vm.max_map_count [65530] likely too low, increase to at least [262144]
  # ... see this
  # https://github.com/elastic/elasticsearch-docker/blob/master/README.md#osx-with-docker-toolbox
  elastic:
    container_name: elastic
    build:
      context: services/elastic/
    volumes:
      - "./util:/util/"
    ports:
      - "${ELASTIC_PORT}:${ELASTIC_PORT}"
    command: >
      elasticsearch
        -Edefault.http.port=${ELASTIC_PORT}
        -Edefault.network.host=0.0.0.0
        -Edefault.transport.host=0.0.0.0
        -Edefault.cluster.name=ccc-es
        -Edefault.node.name=central
